# Menu header
menu_header: "Gracias por comunicarte con <strong>iKono Telecomunicaciones.</strong><br>Para nosotros es un gusto poder ayudarte 😀<br><br><i>Por favor selecciona una de las siguientes opciones:</i><br><br>"

# Submenu header
submenu_header: "<i>Por favor selecciona una de las siguientes opciones para la ciudad de: <b>{menu_option}<b> </i><br><br>"

# Submenu level three header
submenu_lv_three_header: "<i>Opciones disponibles para: <b>{menu_option}</b></i><br><br>"

# No agents message
no_agents_message: "Hola! Recuerda que nuestro horario de atención por este medio es de lunes a viernes de 8am a 6pm<br><br>Que tengas un excelente día! 😊"

# Menu options simple (# form one)

# menu_options:
#   # Usar esta si se quiere un QuickReply
#   interactive_message:
#     type: "quick_reply"
#     text: "Hola, bienvenido al canal de WhatsApp de <b>Provisión</b>.<br>" # Longitud maxima no encontrada :)
#     header: "Hola mundo" # Longitud maxima 60 caracteres
#     caption: "Somos Holanda" # Longitud maxima 60 caracteres
#     # La cantidad maxima de opciones en los menús tipo quick_reply es de 3
#     upload_file:
#       # Archivos soportados [image, document, video]
#       # para tener un menu simple, dejar estas opciones vacias
#       url_preview: ""
#       file_type: ""
#       filename: ""
#   # Usar esta si se quiere un ListReply
#   interactive_message:
#     type: "list_reply"
#     title: "Aleluya 2" # Longitud maxima 60 caracteres
#     body_text: "Esta es una hermosa prueba" # Longitud maxima no encontrada :)
#     title_global_button: "Abrir" # Longitud maxima 20 cracteres
#     optional_data:
#       # La cantidad maxima de opciones en los menús tipo lista es de 10
#       chunk_size: 10
#       # Título usado en los subsiguientes mensajes interactivos cuando opciones > chunk_size
#       other_options_title: "" # Longitud maxima 60 caracteres
#       # Título usado en los subsiguientes mensajes interactivos cuando opciones > chunk_size
#       other_options_body: "Mas opciones" # Longitud maxima no encontrada :)
#     section_data:
#       title: "Titulo de seccion" # Longitud maxima 24 caracteres
#       subtitle: "Subitulo de seccion" # Longitud maxima no encontrada :) (ademas creo que no existe, pero gupshup la usa)
#   "1":
#     text: "Beneficios al asociado"
#     room_id: "!xFIbeagfmFNxmweymH:provision.com.co"
#     no_agents_message: ""
#   "2":
#     text: "Cancelaciones"
#     room_id: "!BQmqUniDXtEJEaNtbG:provision.com.co"
#     no_agents_message: ""
#   "3":
#     text: "Cambios Intermediario"
#     room_id: "!FGWqmHsYgrwWXAuLEp:provision.com.co"
#     no_agents_message: ""
#   "4":
#   text: "Cartera"
#   options:
#     interactive_message:
#       type: "list_reply"
#       title: "Aleluya 2"
#       body_text: "Esta es una hermosa prueba"
#       title_global_button: "Abrir"
#       optional_data:
#         chunk_size: 10
#         other_options_title: ""
#         other_options_body: "Mas opciones"
#       section_data:
#         title: "Titulo de seccion"
#         subtitle: "Subitulo de seccion"
#     "1":
#       text: "Sura, Allianz, Mapfre" # Longitud maxima 24 cracteres
#       description: "Premiaciones y planes de incentivos" # Longitud maxima 72 carcateres
#       room_id: "!rROHItYbgksnRyiJZP:provision.com.co"
#       no_agents_message: ""
#     "2":
#       text: "Otras aseguradoras"
#       room_id: "!iNqLaRptJCFkuEdtWw:provision.com.co"
#       no_agents_message: ""
#     "0":
#       text: "Ir al menú anterior"


menu_options:
  "1":
    text: "Para comunicarte con **Ventas** 🛒"
    room_id: "!GidfUPmvENZXOGRvvB:darknet"
    no_agents_message: "No hay agentes en **Ventas** "
    custom_message: "Mensaje personalizado"
  "2":
    text: "Para solicitar **Soporte** 🙋"
    room_id: "!yaHyAKPWYtVJSicdeC:darknet"
    join_agent_message: "{agentname} será tu asesor"
    no_agents_message: ""
  "3":
    text: "Si requieres **Servicio al cliente** 💁<200d>♀️"
    room_id: "!mecvMBiHLULHQKOWjU:darknet"
    join_agent_message: ""
    no_agents_message: "No hay agentes en **Servicio al cliente** 🤷<200d>♀️"
  "4":
    text: "**Administración**"
    room_id: "!UIjPlZcxTSxUwtrgaL:darknet"
    join_agent_message: ""
    no_agents_message: "Mensaje personalizado para Administración cuando no hay agentes"

# Menu options with submenus (# form two)
#menu_options:
#  "1":
#    text: "Medellin"
#    submenu_header: "<i>Bienvenido al menú dos usted esta en la opción: <b>{menu_option}</b><i><br><br>"
#    options:
#      "1":
#        text: "Beneficios al asociado"
#        text_field: true
#        placeholder:
#          - ""
#        error_message:
#          - "El valor ingresado es incorrecto"
#        regex:
#          - "([a-zA-Z0-9_-])"
#        send_email: true
#        email_subject: ""
#        email_header: ""
#      "2":
#        text: "Cancelaciones"
#        image:
#          file_name: "New image"
#          url: "mxc://localhost/wRTciwiOvMjgOODjJCmcstHS"
#      "3":
#        text: "Cambios Intermediario"
#        room_id: "!--:localhost"
#        no_agents_message: ""
#      "4":
#        text: "Cartera"
#        options:
#          "1":
#            text: "Sura, Allianz, Mapfre"
#            room_id: "!--:localhost"
#            no_agents_message: ""
#          "2":
#            text: "Otras aseguradoras"
#            room_id: "!--:localhost"
#            no_agents_message: ""
#          "0":
#            text: "Ir al menu anterior"
#      "0":
#        text: "Ir al menu anterior"
#  "2":
#    text: "Bogotá"
#    options:
#      "1":
#        text: "Beneficios al asociado"
#        options:
#          "1":
#            text: "Gestión líneas celulares"
#            room_id: "!--:localhost"
#            no_agents_message: ""
#          "2":
#            text: "Otras solicitudes"
#            room_id: "!--:localhost"
#            no_agents_message: ""
#          "0":
#            text: "ir al menu anterior"
#      "2":
#        text: "Cartera"
#        room_id: "!--:localhost"
#        no_agents_message: ""
#      "3":
#        text: "Comisiones"
#        room_id: "!--:localhost"
#        no_agents_message: ""
#      "4":
#        text: "Compensaciones"
#        options:
#          "1":
#            text: "Anticipos de comisiones y auxilios"
#            room_id: "!--:localhost"
#            no_agents_message: ""
#          "2":
#            text: "Todo lo referente al pago de la compensacion, diferente a reclamos de comisiones"
#            room_id: "!--:localhost"
#            no_agents_message: ""
#          "0":
#            text: "Ir al menu anterior"
#      "0":
#        text: "Ir al menu anterior"
#
#goodbye message, it sends when user choose a custom_message or an api request.
#it's optional
goodbye_message: "Este es un mensaje de despedida"

# Is used to resolve chat if menu is in custom_message option
resolve_on_custom_message: True
send_message_on_resolve: True

# key_phrase, when the client select a special options and this wait
# a response, the key_phrase is use to compare the input message to distribute the chat
key_phrase: ""

# pause_menu:
#   pause_phrase: ""
#   pause_message: "😊"
#   resume_phrase: ""
#   resume_user_id: "@menubot:darknet"
#   resume_message: "😊"

# opt-in options
optin:
  ask_optin: false
  # save customer information in the database
  save_optin: true
  show_menu_if_not_accepted: false
  no_optin_message: "Gracias por contactarte con nosotros"
  menu_header: "Aceptas recibir mensajes de iKono Telecomunicaciones S.A.S. a través de WhatsApp?"
  menu_options:
    "1": "ACEPTO"
    "2": "NO ACEPTO"
  menu_footer: ""
  # if this is empty, the bridge is extracted from userid prefix. It is used for customers
  # ported from mautrix to gupshup, to send gs as the bridge insted of mx
  bridge: ""
  company_phone: "57312345678"

# bridge that do not allow formatting of messages
# if no_formatting_user_prefixes don't exist, so all message will be formatted
no_formatting_user_prefixes:
  - "ig"

# Regex to extract user phone number from matrix user ID
username_regex: "^@(?P<user_prefix>.+)_(?P<phone_number>[0-9]{8,}):.+$"

# timeout when menu send two messages consecutive
message_delay: 1 # seconds

# show no agents message timeout(seconds)
no_agents_message_timeout: 30

# Continue talking
# wrapup:
#   menu_header: "<br><br>¿Necesitas más información?<br><br><i>Elige cualquiera de las siguientes opciones: (Digita únicamente el número que corresponda, ejemplo: 1)</i><br>"
#   go_back: "1"
#   distribute: "2"
#   finish: "3"
#   menu_options:
#     "1":
#       text: "Regresar al menú"
#     "2":
#       text: "Prefiero hablar con un asesor"
#       room_id: "!mIiSwJzWbfCVSDKfEZ:localhost"
#       no_agents_message: ""
#     "3":
#       text: "Me ha quedado todo claro"

# agent control room, all agents must be here
control_room_id: ""

# room where agents are available to respond when there's no menu
available_agents_room: ""

#custom join message that sends when don't have menu
no_menu_join_agent_message: ""

# prefix of commands
command_prefix: "!menubot"

# prefix of commands for the acd
acd_command_prefix: "!acd"

# bots to ignore messages from
bots:
  - "@whatsappbot:darknet"
  - "@instagrambot:darknet"
  - "@gupshupbot:darknet"
  - "@acd:darknet"
  - "@acd1:darknet"
  - "@acd2:darknet"
  - "@acd3:darknet"
  - "@acd4:darknet"
  - "@acd5:darknet"
  - "@admin:darknet"

# time to wait until send whatsapp menu again after subsequent messages
menu_delay: 5

# MenuBot will send below commands to interact with any WA bridge
bridges:
  gupshup:
    # Prefix to be listened by bridge
    prefix: "!gs"
    user_prefix: "gswa"
    # Interactive Message
    interactive_message_command: "interactive-message"
  mautrix:
    # Prefix to be listened by bridge
    prefix: "!wa"
    # Prefix for users created
    user_prefix: "mxwa"

# properties to configure the chat resolver for inactivity (in seconds)
# inactivity_chat:
#   # Time in which the task starts
#   chat_timeout: 900
#   # Message for resolve chat for inactivity
#   closing_message: "La conversación ha finalizado por inactividad"
#   # Chat closure warning message
#   warning_message: "<b>Por favor elija una opción</b> o el chat se cerrará automáticamente por inactividad"
#   # Time between attempts
#   time_between_attempts: 300
#   # number tries actives chats
#   tries_number: 2
#   # resolve chat notice
#   resolve_chat_notice: "Chat resuelto"

# api data
api:
  base_url: "https://api.ikono.im"
  login_url: "/v1/auth/token"
  customers_url: "/v1/customers"
  optin_path: "/v1/opt_in"
  password: ""

# Endpoint base de la provisioning del acd-as
acd_as:
     base_url: "http://acd-as:29601/provision"

#external_api data
# external_api:
#   base_url: ""
#   login_url: ""
#   user_id: ""
#   password: ""
#   error_codes:
#     _EXAMPLE_: "Mensaje de error personalizado"

# SMTP dad to send emails
# smtp_data:
#   user: "nplyplease@localhost.com"
#   password: ""
#   host: "smtp.gmail.com"
#   port: 25

# # Mailing data to send emails
# mailing_data:
#   from: ""
#   # Can be array to send to one or more email addresses
#   to: [""]

# Options for connecting to the bot's Matrix account
matrix:
  # The Matrix User ID of the bot account
  user_id: "@menubot1:darknet"
  # Matrix account password
  # user_password: "xxx"
  # The access token of the bot account
  access_token: "syt_bWVudWJvdDE_tYmwrfsQjtfrjKiaAPmh_3jWHcU"
  # The URL of the homeserver to connect to
  homeserver_url: http://synapse:8008
  # The device ID that is **non pre-existing** device
  # If this device ID already exists, messages will be dropped silently in encrypted rooms
  device_id: MENUBOTDEVICE
  # What to name the logged in device
  device_name: menubot-device
  # End-to-end encryption support
  #
  # Enabling this requires installing the matrix-nio encryption dependencies
  # as described here: https://github.com/poljar/matrix-nio#installation
  enable_encryption: false

storage:
  # The path to the database
  database_filepath: "store/menubot.db"
  # The path to a directory for internal bot storage
  # containing encryption keys, sync tokens, etc.
  store_filepath: "store"

logging:
  version: 1
  formatters:
    normal:
      format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: normal
      filename: logs/menubot.log
      maxBytes: 10485760
      backupCount: 10
    console:
      class: logging.StreamHandler
      formatter: normal
  loggers:
    menubot:
      level: DEBUG
      handlers: [file, console]
  root:
    level: DEBUG
    handlers: [file, console]

