repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        language_version: python3
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: black (code formatting)
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (import sorting)
        language_version: python3
  - repo: local
    hooks:
      - id: check-setup-version
        name: Check python setup version
        entry: python3 setup.py --version
        language: system
