version: "3.9"

# CORRER ESTE COMANDO ANTES DE HACER EL up -d ::: docker-compose run --rm -e SYNAPSE_SERVER_NAME=darknet -e SYNAPSE_REPORT_STATS=no synapse generate

# NOTA EJECUTAR DOS VECES ESTE COMANDO
# CORRER ESTE COMANDO ANTES DE HACER EL up -d ::: docker run --rm -v $(pwd)/configs/gupshup:/data ikonoim/mautrix-gupshup:stable

# PARA CREAR LA DB DEL Synapse
# CREATE DATABASE synapse ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0 OWNER ikono;

# Si sale el error PermissionError: [Errno 13] Permission denied: '/opt/docker-run.sh' usar ::: sudo chmod 755 menu-bot/docker-run.sh
services:
  synapse:
    image: matrixdotorg/synapse:v1.56.0
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./synapse:/data/

    ports:
      - 8008:8008

  acd-as:
    image: ikonoim/acd-appservice:testing
    build: .
    restart: unless-stopped
    volumes:
      - .:/opt/acd-appservice
      - ./acd:/data
      # - /home/alejo/Documentos/ikono/python/mautrix:/usr/lib/python3.9/site-packages/mautrix
    depends_on:
      - postgres
      - synapse
    # entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." /opt/acd-appservice/docker-run.sh
    ports:
      - 29601:29601

  menubot:
    image: ikonoim/menubot:stable
    restart: unless-stopped
    volumes:
      - ./menubot/config:/opt/config
      - ./menubot/store:/opt/store
      - ./menubot/logs:/opt/logs

    depends_on:
      - synapse

  whatsapp:
    image: dock.mau.dev/mautrix/whatsapp:v0.6.0
    restart: unless-stopped
    volumes:
      - ./whatsapp:/data
    depends_on:
      - synapse
      - postgres

  instagram:
    image: dock.mau.dev/mautrix/instagram:v0.2.0
    restart: unless-stopped
    volumes:
      - ./instagram:/data
    depends_on:
      - synapse
      - postgres

  gupshup:
    image: bramenn/gupshup-matrix:latest
    restart: unless-stopped
    volumes:
      - ./gupshup:/data
    depends_on:
      - synapse
      - postgres

  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: secretfoo
      POSTGRES_DB: acd_db
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./schemas:/var/lib/postgresql/data
