version: "3.9"

# CORRER ESTE COMANDO ANTES DE HACER EL up -d ::: docker-compose run --rm -e SYNAPSE_SERVER_NAME=darknet -e SYNAPSE_REPORT_STATS=no synapse generate

# NOTA EJECUTAR DOS VECES ESTE COMANDO
# CORRER ESTE COMANDO ANTES DE HACER EL up -d ::: docker run --rm -v $(pwd)/configs/gupshup:/data ikonoim/mautrix-gupshup:stable

# PARA CREAR LA DB DEL Synapse
# CREATE DATABASE synapse ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0 OWNER ikono;

# Si sale el error PermissionError: [Errno 13] Permission denied: '/opt/docker-run.sh' usar ::: sudo chmod 755 menu-bot/docker-run.sh
services:
  synapse:
    image: matrixdotorg/synapse:v1.56.0
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./synapse:/data/

    ports:
      - 8008:8008

  acd-az:
    image: ikonoim/acd-appservice:testing
    build: .
    restart: unless-stopped
    volumes:
      - .:/opt/acd-appservice
      - ./data:/data
      # - /home/alejo/Documentos/ikono/python/mautrix:/usr/lib/python3.9/site-packages/mautrix
    depends_on:
      - acd-az-db
      - synapse
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." /opt/acd-appservice/docker-run.sh
    ports:
      - 26666:26666

  menubot:
    image: ikonoim/menubot:stable
    restart: unless-stopped
    volumes:
      - ./menubot/menubot_config.yaml:/opt/config/config.yaml
      #- ./menubot/menubot.db:/opt/store/menubot.db
      - ./menubot/logs:/opt/logs

    depends_on:
      - synapse

  whatsapp:
    image: dock.mau.dev/mautrix/whatsapp:v0.4.0
    restart: unless-stopped
    volumes:
      - ./whatsapp:/data

  acd-az-db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ikono
      POSTGRES_PASSWORD: secretfoo
      POSTGRES_DB: acd_db
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./schemas-acd_az:/var/lib/postgresql/data
