version: "3.9"

# CORRER ESTE COMANDO ANTES DE HACER EL up -d ::: docker-compose run --rm -e SYNAPSE_SERVER_NAME=darknet -e SYNAPSE_REPORT_STATS=no synapse generate

# NOTA EJECUTAR DOS VECES ESTE COMANDO
# CORRER ESTE COMANDO ANTES DE HACER EL up -d ::: docker run --rm -v $(pwd)/configs/gupshup:/data ikonoim/mautrix-gupshup:stable


# Si sale el error PermissionError: [Errno 13] Permission denied: '/opt/docker-run.sh' usar ::: sudo chmod 755 menu-bot/docker-run.sh
services:
  synapse:
    image: matrixdotorg/synapse:v1.56.0
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./synapse:/data/
    depends_on:
      - synapse-db
    ports:
      - 8008:8008

  synapse-db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ikono
      POSTGRES_PASSWORD: secretfoo
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./schemas-synapse:/var/lib/postgresql/data
    ports:
      - 26666:26666
  acd-az:
    build: .
    restart: unless-stopped
    volumes:
      - .:/opt/acd-program
    depends_on:
      - acd-az-db
      - synapse
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." /opt/acd-program/docker-run.sh

  acd-az-db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ikono
      POSTGRES_PASSWORD: secretfoo
      POSTGRES_DB: acd_db
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./schemas-acd_az:/var/lib/postgresql/data