[tool.isort]
profile = "black"
line_length = 99
multi_line_output=3
include_trailing_comma=true

[tool.black]
line-length = 99
target-version = ["py39"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
